apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingcenter
  labels:
    app: testingcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testingcenter
  template:
    metadata:
      labels:
        app: testingcenter
    spec:
      containers:
        - name: testingcenter
          image: "879772956301.dkr.ecr.ca-central-1.amazonaws.com/user10-testingcenter:latset"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
